"""Add chat session and message tables

Revision ID: 0bf1131d9d9a
Revises: d90e057194ae
Create Date: 2026-01-28 22:35:43.179455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf1131d9d9a'
down_revision = 'd90e057194ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesi_chat',
    sa.Column('id_sesi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul', sa.String(length=100), nullable=True),
    sa.Column('nomor_induk_mahasiswa', sa.String(length=20), nullable=False),
    sa.Column('waktu_dibuat', sa.DateTime(), nullable=True),
    sa.Column('waktu_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nomor_induk_mahasiswa'], ['mahasiswa.nomor_induk_mahasiswa'], ),
    sa.PrimaryKeyConstraint('id_sesi')
    )
    op.create_table('pesan_chat',
    sa.Column('id_pesan', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesi', sa.Integer(), nullable=False),
    sa.Column('pengirim', sa.String(length=10), nullable=False),
    sa.Column('isi_pesan', sa.Text(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sesi'], ['sesi_chat.id_sesi'], ),
    sa.PrimaryKeyConstraint('id_pesan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pesan_chat')
    op.drop_table('sesi_chat')
    # ### end Alembic commands ###
