"""Initial migration

Revision ID: 7bc430d80a3c
Revises: 
Create Date: 2025-12-13 19:32:11.984938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc430d80a3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id_admin', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('kata_sandi', sa.String(length=255), nullable=False),
    sa.Column('nomor_whatsapp', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('email')
    )
    op.create_table('mahasiswa',
    sa.Column('nomor_induk_mahasiswa', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('kata_sandi', sa.String(length=255), nullable=False),
    sa.Column('nomor_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('status_akun', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('nomor_induk_mahasiswa'),
    sa.UniqueConstraint('email')
    )
    op.create_table('riwayat',
    sa.Column('id_riwayat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediksi_kategori', sa.String(length=50), nullable=False),
    sa.Column('tingkat_keyakinan', sa.Float(), nullable=False),
    sa.Column('respons_bot', sa.Text(), nullable=False),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.Column('nomor_induk_mahasiswa', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['nomor_induk_mahasiswa'], ['mahasiswa.nomor_induk_mahasiswa'], ),
    sa.PrimaryKeyConstraint('id_riwayat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat')
    op.drop_table('mahasiswa')
    op.drop_table('admin')
    # ### end Alembic commands ###
